### ISSUE TITLE
createTransferVC method for invokeTelephonyIntegrationApi does not include Custom Attributes

### ISSUE THREAD

**Issue by LorneCurrie** [service-cloud-voice/ServiceCloudVoiceLambdas#10]
When an agent handles an inbound voice call, we use the `invokeTelephonyIntegrationApi` function with the `createVoiceCall` method to create a Voice Call record.  This includes any custom contact attributes that were set in the call flow.  If a caller is then transferred to another queue and in the transfer, the flow happens to update some of the attributes, when we call the `invokeTelephonyIntegrationApi` function with the method `createTransferVC` the custom contact attributes are not added to the new VC Transfer object.  This hinders agents as there may be information collected in the transfer process that we need to surface to an agent.  Is it possible to have the customer attributes added to the Transfer VC object at the creation time?

Note: We know that the Transfer VC object is updated once the CTR is picked up from Kinesis.

**Comment by jinalkathiara** [comment]
Thanks for the feedback. 
Unfortunately this is a gap and thanks for highlighting this. we will fix this in the upcoming lambda version and contact center update. 

Until then, you can manually modify the lambda to update custom attributes into your lambda copy.

**Comment by sonymammen-vf** [comment]
Thanks Jinal. Same issue is applicable for Callback as well. The attribute is not passing over for a callback. It would be great if we can fix for callback as well. 
What we are trying to passthrough is the QueueName, which is generally available after wrapping up the call. So we are passing the QueueName as a custom contact attribute

**Comment by bobSFtrailhead** [comment]
Hi @jinalkathiara do you have an update as to when this will be implemented?

**Comment by jinalkathiara** [comment]
As of now this is not have an update. I will update one more time once I know the ETA.

**Comment by rob-sanuk** [comment]
@jinalkathiara - can you confirm that this is a change to the API for the new release (https://help.salesforce.com/s/articleView?id=release-notes.rn_voice_pass_custom.htm&release=244&type=5) and that this will be accepted in the same object (callAttributes) that is passed to the API and accepted for the create Voicecall method

![image](https://user-images.githubusercontent.com/102224852/234812158-6ba8afba-7273-4008-8eb9-80e838b0e44b.png)

**Comment by jinalkathiara** [comment]
Yes that's correct. These changes are live now and what you have mentioned is accurate. Closing this issue.
