### ISSUE TITLE
Cloud Formation template 

### ISSUE THREAD

**Issue by rob-sanuk** [service-cloud-voice/ServiceCloudVoiceLambdas#18]
Could the Cloud Formation Template for the serverless application please also be added to the repository to ensure that the correct version is used with the lambdas?
Thank you

**Comment by jinalkathiara** [comment]
We will do that once we release latest version.

**Comment by idris-laabassi** [comment]
Hi @jinalkathiara we really need the Cloud Formation Template for version 9.1, I'm struggling in upgrading an old version of the serverLess app as the amazon repository contains an old version 9.0.1 https://us-east-1.console.aws.amazon.com/lambda/home?region=us-east-1#/create/app?applicationId=arn:aws:serverlessrepo:us-east-1:317368162107:applications/ServiceCloudVoiceLambdas
That version doesn't contain the new lambdas that you released 21 days ago (example the authKeysSSMUtil which is a key function to update key pairs automatically from service cloud voice). Thanks for your support

**Comment by jinalkathiara** [comment]
Added cloud-formation template for the https://github.com/service-cloud-voice/ServiceCloudVoiceLambdas/pull/24

This is for the contact center version 10.0
