### ISSUE TITLE
ContactLensStream Kinesis Stream - Association - Post Deployment Step?

### ISSUE THREAD

**Issue by rob-sanuk** [service-cloud-voice/ServiceCloudVoiceLambdas#19]
We have installed the serverless repository from the github repo for version 9.0.1:
https://serverlessrepo.aws.amazon.com/applications/us-east-1/317368162107/ServiceCloudVoiceLambdas

There is a successful install but it is not clear how the ContactLensStream Kinesis stream connects to the real-time contact analysis to produce the transcription in Salesforce.

Step 3 in this document appears to be what is required but we would like confirmation:
https://docs.aws.amazon.com/connect/latest/adminguide/enable-contact-analysis-segment-streams.html

**Comment by jinalkathiara** [comment]
This is one of the known bug and we are planning to fix this in the Spring 23 release.

**Comment by jinalkathiara** [comment]
This is fixed with the 11.0 version. I am closing this issue.

**Comment by wilfgr-sanuk-aws** [comment]
Great, thanks!
