### ISSUE TITLE
Lambda and Connect CW Dashboard issue

### ISSUE THREAD

**Issue by wilfgr-sanuk-aws** [service-cloud-voice/ServiceCloudVoiceLambdas#20]
Following deployment of the 9.1 code, the CW dashboards no longer function as expected. This appears to be down to a change when referring to the FunctionName within the Template.yaml.

To remediate we've rolled back to the previous Dashboard version, which fixes the issue.

**Comment by jinalkathiara** [comment]
@wilfgr-sanuk-aws Yes apologies for the breakage. we are aware and very soon we are getting latest 10.0.0 version, which should have the fix.

**Comment by jinalkathiara** [comment]
Created the PR with the contact center 10.0 release. This issue should be fixed in the V10.0

**Comment by jinalkathiara** [comment]
https://github.com/service-cloud-voice/ServiceCloudVoiceLambdas/pull/23/files

**Comment by jinalkathiara** [comment]
Closing this issue.
