### ISSUE TITLE
invokeTelephonyIntegrationApi.executeOmniflow fails after 10.0 update

### ISSUE THREAD

**Issue by iberever** [service-cloud-voice/ServiceCloudVoiceLambdas#25]
This change in 10.0 in
https://github.com/service-cloud-voice/ServiceCloudVoiceLambdas/blob/2017940e0b859c8dd01e6b13aa13bdfe449ec265/invokeTelephonyIntegrationApi/handler.js#L115-L116

is causing the call to be made to the SF API with `/voiceCall/undefined/omniFlow`.

The `===` check is too restrictive as if no parameter is sent, the variable would be `undefined`, not `null`.
Best choice is to check for a `falsy` value instead. 

like so:
```javascript
const contactIdParam = contactId || event.Details.ContactData.ContactId;
```

**Comment by jinalkathiara** [comment]
Fixed in the 10.1 version, We will release 11.0 version which should have this fix.
