### ISSUE TITLE
Serverless Application yaml does not include Voicemail lambdas

### ISSUE THREAD

**Issue by jasondearingcnx** [service-cloud-voice/ServiceCloudVoiceLambdas#26]
The SAR app published on AWS, and the yaml in /ServerlessApplication/ of this repo do not reference or install the Voicemail-related lambdas or resources

**Comment by jinalkathiara** [comment]
Unfortunately VoiceMail lambdas are not part of the 10.x.x serverless application. It will be part of the 11.x.x version which we are expecting to release sometime during February.

**Comment by jinalkathiara** [comment]
This issue is fixed with the 11.0 version. Closing this issue.
