### ISSUE TITLE
Object Tag Error

### ISSUE THREAD

**Issue by NFdgomez** [service-cloud-voice/ServiceCloudVoiceLambdas#27]
We're trying to enable voicemail support for a BYOA instance and we're running into this error for the voiceMailAudioProcessing Lambda:

"errorType": "Runtime.UnhandledPromiseRejection", "errorMessage": "BadRequest: Object tags cannot be greater than 10", "reason": { "errorType": "BadRequest", "errorMessage": "Object tags cannot be greater than 10"

We are only using 3 tags total not more than 10 so we're not sure why this error pops up.

**Comment by jinalkathiara** [comment]
If possible can you provide the event for which VoiceMailAudio Processor lambda gets called ? 
This seem like a bug. @dlouvton

**Comment by NFdgomez** [comment]
We can close this issue, we figured out that it was a permissions issue on the Amazon Connect side. Once we resolved it, the error never displayed again.

**Comment by dlouvton** [comment]
Hi @NFdgomez, can you add some details on what was the permissions issue and how it got resolved?
