### ISSUE TITLE
Issue updating from 10.1

### ISSUE THREAD

**Issue by dcarbonetti** [service-cloud-voice/ServiceCloudVoiceLambdas#30]
Trying to perform an update to the applications and getting the following event which is triggering a cancel and rollback

2023-02-23 16:06:22 UTC+1100 | kvsTranscriberVersion86a091a95c | CREATE_FAILED | A version for this Lambda function exists ( 2 ). Modify the function to create a new version.

From what i can tell there have been no changes to the lambda so not sure why this is happening

**Comment by jinalkathiara** [comment]
I believe you might have a failure during 10.1 and the rollback didn't completed successfully. If you have used the correct IAM permissions for Salesforce to assume that role then you shouldn't see this error.

If you are using serverless application, make sure that the rollback for the failure happens successfully and you are having a clearner cloudformation status before upgrade.

**Comment by jinalkathiara** [comment]
Did you get resolution ? I am closing this issue.
