### ISSUE TITLE
Relationship between SAR version and more public version confirmation

### ISSUE THREAD

**Issue by vgw-chriskruger** [service-cloud-voice/ServiceCloudVoiceLambdas#36]
My organisation is planning to manage the deployment of this application via Terraform. 

I have noted a slight discrepancy between public versioning and the semantic versioning within the serverless application repository. 

The public releases seem to be 11.1, 11.0, 10.1, 10.0 etc as highlighted [here](https://help.salesforce.com/s/articleView?id=000390799&type=1) and in the commit messages within this repository. 

However the serverless application repository lists the semantic versions as 

```
[
  "1.0.1",
  "1.0.2",
  "10.0.0",
  "10.0.1",
  "11.0.0",
  "11.0.1",
  "12.0.0",
  "2.0.0",
  "2.0.1",
  "9.0.0",
  "9.0.1"
]
```

I am assuming 11.1 matches the 11.0.1 SAR version? 

Also I would like to suggest that this repository starts using semantic version release tagging just so it is easy to see what the changes are etc.

**Comment by jinalkathiara** [comment]
Yes that is correct. 11.1 matches the 11.0.1 SAR version.
