### ISSUE TITLE
Pass-in at stack level - SALESFORCE_AUTH_ENDPOINT & SALESFORCE_REST_API_ENDPOINT_BASE 

### ISSUE THREAD

**Issue by vgw-chriskruger** [service-cloud-voice/ServiceCloudVoiceLambdas#38]
I have a suggestion:

https://github.com/service-cloud-voice/ServiceCloudVoiceLambdas/blob/main/ServerlessApplication/ServiceCloudVoiceLambdas.yaml#LL200C11-L201C94

It would be good if some of these very likely to be modified variables could be passed in at the top level of the SAM template.  We would like to be able to deploy this application via Terraform more easily using resource directives like https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/serverlessapplicationrepository_cloudformation_stack

**Comment by vgw-chriskruger** [comment]
I have made a PR to this effect. https://github.com/service-cloud-voice/ServiceCloudVoiceLambdas/pull/39

**Comment by jinalkathiara** [comment]
Closing this issue. We have merged your PR.
