### ISSUE TITLE
Configuration documentation is wrong - Configure users in Amazon Connect.

### ISSUE THREAD

**Issue by vgw-chriskruger** [service-cloud-voice/ServiceCloudVoiceLambdas#41]
If I understand correctly the associated documentation for configuring this software is [this document](https://resources.docs.salesforce.com/latest/latest/en-us/sfdc/pdf/support_voice_pt_amazon_connect.pdf).

In the section _Configure Users in Amazon Connect_ (pg 13) the documentation instructs implementors to build a CSV with usernames formed with the follow parameters `$User.Id & '@' & $Organization.Id`.

Using this guidance we configured some users for our AWS Connect instance but we could not successfully take a voice call.

Upon close inspection and comparison with an existing AWS Connect integration with Salesforce we noted that, for that instance, username also included the Salesforce User alias.

Example:

1. The form of usernames as described by the existing documentation. 

```
006Ah000000JK7E@00DAu000000f110
```

2. The form of usernames that appear to work in practice 

```
ckrug@006Ah000000JK7E@00DAu000000f110
```

Unless there are other reasons in play that are not understood by myself and my fellow integrators, it seems that the documentation should reflect that this the alias is required to construct usable AWS Connect Users. 

`$User.Alias & '@' @ $User.Id & '@' & $Organization.Id`

**Comment by jinalkathiara** [comment]
When we launched this product, we were using  following naming scheme.

`006Ah000000JK7E@00DAu000000f110`
so [this document](https://resources.docs.salesforce.com/latest/latest/en-us/sfdc/pdf/support_voice_pt_amazon_connect.pdf) is accurate and you can use this naming scheme. 

With latest contact centers starting with Spring 22 onwards, we started using following naming scheme.
`ckrug@006Ah000000JK7E@00DAu000000f110`

So both naming scheme works. 
Ideally you should check connected application's configuration. as long as connected application is sending the SAML assertion with the **https://aws.amazon.com/SAML/Attributes/RoleSessionName** = **$User.Id & '@' & $Organization.Id.** you should be able to do SSO. 
`

**Comment by vgw-chriskruger** [comment]
Thank you for your reply. I understand this more completely now and why there has been some variation.
