### ISSUE TITLE
HandleContactEvents Lambda sending ContactId with wrong case

### ISSUE THREAD

**Issue by larry-voicefoundry** [service-cloud-voice/ServiceCloudVoiceLambdas#42]
There is an issue with the Lambda that handles contact events and sends cancel omni-flow events to telephony integration Lambda. That function sends the contact id over as [Details.Parameters.ContactID](https://github.com/service-cloud-voice/ServiceCloudVoiceLambdas/blob/169a7180e329afeda947e4f61e1102bbe7f912b0/handleContactEvents/handler.js#L9) but the invokeTelephony lambda expects [Details.ContactData.ContactId](https://github.com/service-cloud-voice/ServiceCloudVoiceLambdas/blob/169a7180e329afeda947e4f61e1102bbe7f912b0/invokeTelephonyIntegrationApi/handler.js#L138) to exist if [Details.Parameters.contactId](https://github.com/service-cloud-voice/ServiceCloudVoiceLambdas/blob/169a7180e329afeda947e4f61e1102bbe7f912b0/invokeTelephonyIntegrationApi/handler.js#L21) doesn’t.

This causes the invoke telephony Lambda to error out when attempting to log on that line. This appears to be causing issues with contacts correctly wrapping up in Salesforce after the contact disconnects.

**Comment by larry-voicefoundry** [comment]
![Screenshot 2023-06-20 at 15 34 37](https://github.com/service-cloud-voice/ServiceCloudVoiceLambdas/assets/101902657/80be9e23-3343-4105-9fbe-acc49dad47b4)
![Screenshot 2023-06-20 at 15 34 58](https://github.com/service-cloud-voice/ServiceCloudVoiceLambdas/assets/101902657/138642c2-d1d7-4cb1-82dc-151f60e6a21a)
![Screenshot 2023-06-20 at 14 37 30](https://github.com/service-cloud-voice/ServiceCloudVoiceLambdas/assets/101902657/5771b213-fe31-405c-a723-3277be5e0f5e)
![Screenshot 2023-06-20 at 15 48 48](https://github.com/service-cloud-voice/ServiceCloudVoiceLambdas/assets/101902657/6dfbb278-a2ca-4b79-a955-1481370a7bb3)

**Comment by jinalkathiara** [comment]
Thanks for pointing this out. I will look into this and update it here.

**Comment by jinalkathiara** [comment]
This is one of the known issue and this will be fixed as part of the Contact Center 13.

**Comment by jinalkathiara** [comment]
This should be fixed with the latest contact center release.
